### ISSUE TITLE
Exposed mongodb+srv credentials

### ISSUE THREAD

**Issue by eth0izzle** [naveenkumar2098/nodejs-passport#1]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@cluster0-5a8z8.mongodb.net` in file [/config/keys.js](https://github.com/naveenkumar2098/nodejs-passport/blob/master/config/keys.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by naveenkumar2098** [comment]
Thank you for the advice. :)
